---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CLUSTER_NAME
  region: AWS_REGION
  tags:
    project: linkedin-learning

nodeGroups:
  - name: WORKER_NODE_NAME
    instanceType: EC2_INSTANCE_TYPE
    desiredCapacity: NUMBER_OF_NODES
  # - name: ng-2
  #   instanceType: m5.xlarge
  #   desiredCapacity: 2
  
